# Initialization

In [3]:
import os, sys
import time
import numpy as np
import pandas as pd
import random
from scipy import stats as st
import itertools
import operator

import torch

from tqdm.notebook import trange
from tqdm import tqdm

random_state = np.random.RandomState(2020)

In [4]:
# get currently working directory
base_dir = os.getcwd()

# load functions from other notebooks
helpers_file = os.path.join(base_dir, 'helpers.ipynb')
%run $helpers_file

# Load spotlight module
for p in ['../spotlight_ext']:
    module_path = os.path.abspath(os.path.join(base_dir, p))
    if module_path not in sys.path:
        sys.path.append(module_path)

# Load Dataset

## Models

In [5]:
lstm_model = load_model(model_type='entire')
pooling_model = load_model('pooling')

pretrained_models = {
    'lstm': lstm_model,
    'pooling': pooling_model,
}

## Dataset

In [6]:
from spotlight.cross_validation import random_train_test_split
from spotlight.datasets.movielens import get_movielens_dataset

# get dataset
dataset = get_movielens_dataset(variant='1M')
train, test = random_train_test_split(dataset, random_state=random_state)

max_sequence_length = 20
train = train.to_sequence(max_sequence_length=max_sequence_length)
test = test.to_sequence(max_sequence_length=max_sequence_length)

# Genetic Search

target item is 324 in this test case, top k is 10

In [7]:
test_interaction = test.sequences[test.user_ids == 3][0].copy()
test_interaction = test_interaction[test_interaction != 0]
test_interaction

array([197, 124, 125, 190, 114, 186, 196,  59, 200, 191, 177], dtype=int32)

In [8]:
len_test_interaction = len(test_interaction)
len_test_interaction

11

In [9]:
prediction = lstm_model.predict(test_interaction)
prediction[test_interaction] = -StaticVars.FLOAT_MAX
rk_data = st.rankdata(-prediction, method='ordinal')
rk_data[0:10]

array([1089,  324, 1218,  460,  313,   12,   93,  557,   85,  283])

## Random CF candidate selection

In [10]:
import numpy as np

def generate_random_sublists(original_list, sublists_info):
    result_sublists = []
    rng = np.random.default_rng(seed=2020)  # Seed for reproducibility

    for length, count in sublists_info.items():
        generated_sublists_for_length = set()

        while len(generated_sublists_for_length) < count:
            sublist = tuple(rng.choice(original_list, length, replace=False))
            generated_sublists_for_length.add(sublist)

        result_sublists.extend(np.array(list(sublist)) for sublist in generated_sublists_for_length)

    return result_sublists


In [11]:
sublists_info ={
    5:5,
    6:5,
    7:5,
    8:5,
    9:5,
    10:5
}

In [12]:
first_gen = generate_random_sublists(test_interaction, sublists_info)

In [13]:
first_gen

[array([ 59, 197, 190, 196, 200], dtype=int32),
 array([190, 186, 196, 197,  59], dtype=int32),
 array([125, 190, 177,  59, 186], dtype=int32),
 array([190, 197, 124, 191, 196], dtype=int32),
 array([200, 125, 196, 124, 191], dtype=int32),
 array([197, 124, 196, 177, 191, 186], dtype=int32),
 array([197, 190,  59, 124, 177, 191], dtype=int32),
 array([196, 177, 197, 125, 114,  59], dtype=int32),
 array([191, 190, 186, 114, 200, 197], dtype=int32),
 array([ 59, 200, 177, 191, 114, 186], dtype=int32),
 array([191, 177,  59, 124, 196, 186, 125], dtype=int32),
 array([125, 196, 124, 114, 197, 191, 177], dtype=int32),
 array([114, 177, 125, 196, 124, 186,  59], dtype=int32),
 array([124, 186, 177, 196, 200,  59, 190], dtype=int32),
 array([186, 191, 125, 190, 114, 200, 197], dtype=int32),
 array([124, 125, 177,  59, 190, 186, 114, 197], dtype=int32),
 array([197, 196, 125, 191, 124, 177, 114, 186], dtype=int32),
 array([125, 124, 197, 196, 177, 190, 200,  59], dtype=int32),
 array([196, 124

In [14]:
import numpy as np

def crossover(first_list, second_list, p_cross):
    # Find the shorter length among the two lists
    length_first = len(first_list)
    length_second = len(second_list)
    shorter_length = min(length_first, length_second)
    
    # Compute the number of crossover points
    num_crossovers = int(shorter_length * p_cross)
    
    # Choose random indices for crossover within the range of shorter length
    rng = np.random.default_rng(seed=2020)
    crossover_indices_first = rng.choice(shorter_length, num_crossovers, replace=False)
    crossover_indices_second = rng.choice(shorter_length, num_crossovers, replace=False)
    
    # Sort the crossover indices
    crossover_indices_first.sort()
    crossover_indices_second.sort()
    
    # Swap the elements at the crossover indices
    for i in range(num_crossovers):
        index_first = crossover_indices_first[i]
        index_second = crossover_indices_second[i]
        first_list[index_first], second_list[index_second] = second_list[index_second], first_list[index_first]
    
    return first_list, second_list



In [18]:
children = crossover(first_gen[-1], first_gen[-2], 0.3)
children

(array([ 59, 190, 114, 177, 200, 191, 197, 124, 186, 196], dtype=int32),
 array([200, 190, 191, 197, 186, 177, 125,  59, 196, 114], dtype=int32))

In [63]:
def compute_yloss(target_score, kth_score):
    print(target_score, kth_score)
    yloss = max(0, target_score / kth_score - 1.0)
    return yloss

def compute_loss(cf, preds, ranking, target_item, top_k):
    yloss = compute_yloss(preds[target_item - 1], preds[ranking[top_k - 1] - 1])
    return yloss

In [81]:
prediction = lstm_model.predict(children[0])
prediction[children[0]] = -StaticVars.FLOAT_MAX
rk_data = st.rankdata(-prediction, method='ordinal')
rk_data[0:10]
# prediction

array([1168, 1066,  234,  810,  649,  100,  329,  315,  620,  258])

In [79]:
st.rankdata([-1, -2, -3, -4, -5, -6, -7, -8, -9, -10], method='ordinal')


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [85]:
prediction[1065]

-0.2649148

In [66]:
compute_loss(children[0], prediction, rk_data, 649, 10)

2.5038397 -0.17980748


0